# Generated by Django 2.2.10 on 2020-06-01 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayNumber',
        ),
        migrations.AlterModelOptions(
            name='visitnumber',
            options={'verbose_name': '访问量', 'verbose_name_plural': '访问量'},
        ),
        migrations.AddField(
            model_name='visitnumber',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='visitnumber',
            name='day_count',
            field=models.IntegerField(default=0, verbose_name='日访问量'),
        ),
    ]
