# Generated by Django 2.2.10 on 2020-06-01 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20200601_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userip',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userip',
            name='ip_country',
            field=models.CharField(default='', max_length=50, verbose_name='ip归属地'),
        ),
        migrations.AddField(
            model_name='userip',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 14, 9, 39, 232967, tzinfo=utc), verbose_name='最后操作时间'),
        ),
    ]
