# Generated by Django 2.2.10 on 2020-06-01 14:48

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20200601_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 14, 48, 26, 887338, tzinfo=utc), verbose_name='最后操作时间'),
        ),
        migrations.AlterField(
            model_name='visitnumber',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
